apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.CI_PROJECT_NAME }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
    # nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    # nginx.ingress.kubernetes.io/session-cookie-hash: md5
    # nginx.ingress.kubernetes.io/upstream-max-fails: 10
    # nginx.ingress.kubernetes.io/upstream-fail-timeout: 5

    # CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, PATH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://{{ .Values.host.main }}"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: 600

    nginx.ingress.kubernetes.io/client-body-buffer-size: 8M
    nginx.ingress.kubernetes.io/proxy-body-size: 8m

    # External Authentication
    # nginx.ingress.kubernetes.io/auth-url: auth
    # nginx.ingress.kubernetes.io/auth-method: POST
    # nginx.ingress.kubernetes.io/auth-signin: '/auth'
    # nginx.ingress.kubernetes.io/auth-response-headers:
    # nginx.ingress.kubernetes.io/auth-request-redirect:

    # Rate limiting
    nginx.ingress.kubernetes.io/limit-connections: 100
    nginx.ingress.kubernetes.io/limit-rps: 100
    nginx.ingress.kubernetes.io/limit-rpm: 100
    nginx.ingress.kubernetes.io/limit-rate-after: 1000
    # nginx.ingress.kubernetes.io/limit-rate:
    # nginx.ingress.kubernetes.io/limit-whitelist:

    # Secure backends
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ALL:!aNULL:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP"

    # Custom timeouts
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60
    # nginx.ingress.kubernetes.io/proxy-send-timeout: 60
    # nginx.ingress.kubernetes.io/proxy-read-timeout: 60
    # nginx.ingress.kubernetes.io/proxy-next-upstream: 60
    # nginx.ingress.kubernetes.io/proxy-next-upstream-tries: 60
    # nginx.ingress.kubernetes.io/proxy-request-buffering: 60

    # gRPC backend
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
  labels:
    app: {{ .Values.CI_PROJECT_NAME }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    pipeline_id: "{{ .Values.CI_PIPELINE_ID }}"
    build_id: "{{ .Values.CI_BUILD_ID }}"
    commit_sha: "{{ .Values.CI_COMMIT_SHA }}"
    component: ingress
spec:
  tls:
  - hosts:
    - {{ .Values.host.main }}
    secretName: {{ .Values.CI_PROJECT_NAME }}-tls
  rules:
  - host: {{ .Values.host.main }}
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: api
          servicePort: 4070
      - path: /*
        backend:
          serviceName: frontend
          servicePort: 80
