.job_template_lint: &job_lint
  script:
  # Install tool
  - apk add --no-cache git openssl

  # install Helm
  - wget https://kubernetes-helm.storage.googleapis.com/helm-$HELM_VERSION-linux-amd64.tar.gz
  - tar -xvf helm-$HELM_VERSION-linux-amd64.tar.gz
  - mv linux-amd64/helm /usr/local/bin/helm
  - helm init -c

  # update charts
  - helm lint $HELM_PATH
  except:
  - branches
  when: on_success

include:
- /templates/job_publish.yml
- /templates/job_deploy.yml
- /templates/job_lint.yml

image: docker:latest
services:
- docker:dind

variables:
  RELEASE_NAME: ingress
  HELM_PATH: ops/Helm/ingress
  HELM_VERSION: v2.7.2
  KUBE_CONTEXT: minikube

stages:
- best_practices
- publish
- deploy

lint:
  type: best_practices
  <<: *job_lint

chart:staging:
  <<: *job_publish
  only:
  - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-rc(?:0|[1-9]\d*)$/

deploy:staging:
  <<: *job_deploy
  only:
  - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-rc(?:0|[1-9]\d*)$/
